### ISSUE TITLE
Git clone issues on your repositories.

### ISSUE THREAD

**Issue by dapoa2021** [bobby-didcoding/python-course-for-beginners#5]
Hello, i was reading the python for beginners you wrote and i got stocked at that point where i need to git clone on my new terminal on vs studio and i copied this " git@github.com:bobby-didcoding/python-course-for-beginners.git " as you have described and type git clone and put that right Infront of it and press enter and i got this error. 

" family@DESKTOP-GEIQH2H MINGW64 /c/Workfolder
$ git clone git@github.com:bobby-didcoding/python-course-for-beginners
Cloning into 'python-course-for-beginners'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. "

Kindly help with possible hint on how to get passed this stage because i am really enjoying the course and would like to follow it up till the end of it, anmd possibly become a good python coder.

Regards,
Ola.

**Comment by bobby-didcoding** [comment]
Hi there,

I think this is due to you using the ssh clone method without an SSH key
against your account. Try using the HTTPS method. If all else fails you can
download as a zipped directory & unpack it locally.

Thanks
Bobby
