### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by MarcusTheDestroyerNZ** [bobby-didcoding/python-course-for-beginners#6]
When I try to clone it into Microsoft Visual Studio Code for Windows, I keep getting this
![image](https://user-images.githubusercontent.com/120174246/206676469-d4f29c1e-7805-4100-af73-b735a8ff2cf0.png)
Can you please help me because I really want to learn how code using python!
Kind regards.

**Comment by bobby-didcoding** [comment]
Hi, do you have GitHub account? You can always download the zip dir 👍

**Comment by MarcusTheDestroyerNZ** [comment]
Thank you so much this ended up working.
Thank you for your time.
